language: php
php:
- 5.6
- 7.0
before_script:
- composer install
- export PATH=./vendor/bin/:$PATH
- git config --global credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script:
- bash .travis-generate-docs.sh
notifications:
  slack:
    secure: mWZfvX4NA+B7ec0r4oEhYcTmjgeVb7AyQ/F50St6/padNvstSLSuzrdVAHpF6+xHcib5/qwkTUrS/RNzuqGWdehJqX7jmLnVBwGiMyW3+1cI72qnH7dZrmgy2jX354y3NTo+fvjjtSVniMta28CvqwXH+G+sNo1VIidxxxcXAzU=
env:
  global:
  - secure: ZCoO8vC5W3k+V3vb7uxsZtROjdikHCxNbvE1ptTvRWjq9tJS9LV5gQVM6f+FNylgPgcQL9qzhd4krrh8fNuriuRotqWd35XH9FW1ISzSMpkADpwDM2t/az/dhucRKc43eDqW8d/XrrvrmqsTYe694jd+lrvcimGeFw0WEfXIHBk=
